### ISSUE TITLE
Minor bug!

### ISSUE THREAD

**Issue by Sc0th** [xbb/apcupsd#1]
Very nice, thank you, one tiny issue:

The GUI demands an number above 0 for 'Battery Level Shutdown (%)' & 'Battery Minutes Shutdown'

However as I only use 'Battery Timeout Shutdown' I would normally set these to 0 in order to disable them.

**Comment by xbb** [comment]
Hi and thanks, I might it fix here but the plugin is already merged (as `-devel` for now) in the official [opnsense-plugin](https://github.com/opnsense/plugins) repository so I will submit a pull request later.

The manual also states that some UPS may report a battery charge level of 0, some users will set `BATTERYLEVEL` to `-1` because of this.

**Comment by xbb** [comment]
Pull request: https://github.com/opnsense/plugins/pull/3022

**Comment by xbb** [comment]
os-apcupsd-devel 0.2 includes the fix, if you installed the package from this fork you can remove it with `pkg remove os-apcupsd-devel` then you can install the official one with `pkg install os-acpupsd-devel`.

If your opnsense version is `21.1.9` you will be able to set `0` for battery level/minutes. If `21.1.10` you can also set `-1`
